### PR TITLE
#Milestone: Testing Calculator

### PR DESCRIPTION
**Pull request by cliftondavies**
### Completed:
- [x] Gitflow
- [x] ESLint
- [x] Stylelint
- [x] Unit tests for calculator.js
- [x] Jest snapshot tests for home, calculator and quote pages.
- [x] Tests for calculator functionality with React Testing Library

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @cliftondavies  :clap: 

### Awesome job so far!! :+1: You have done the unit testing for `calculator.js` and snapshot testing too even though you don't have much to test in `home.js` and `quote.js`

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

**1. Seems you forgot to add the basic styling for the project**
kindly check the list we have under `Styling Calculator `
image
Kindly check out the .pdf on the [pathwright](https://microverse.pathwright.com/library/react-redux-v11/184438/path/step/106376017/)

**2. Do well to update your README file with the correct live demo link.**

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by cliftondavies** [comment]
Thanks, @bellom :+1:

I have added basic styling and updated the live demo link, as requested.

Happy coding!

**Review by SpaYco — APPROVED** [review]
# Project Approved

thank you for making the required changes, your project is now approved!

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by cliftondavies** [comment]
Thanks, @Spayco ! 👍

**Pull request merged**
