### PR TITLE
Milestone 4: Calculations

### PR DESCRIPTION
**Pull request by cliftondavies**
### Completed:
- [x] Gitflow
- [x] ESLint
- [x] Stylelint
- [x] Logic Folder
- [x] calculate.js module
- [x] operate.js module
- [x] App component imports calculate function

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Well done implementing most of the logic @cliftondavies! There are a few changes to make before moving to the next milestone though. These include;

- [ ] The logic for the `+/-` button which should multiply total and next by -1 to make it negative or positive is missing from your `calculate.js` module.
- [ ] The logic for the `%` button should be implemented in the `operate.js` module (turning the number into a percentage based number, `e.g. 95 % == .95`) functions ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone4/performOperate.png))

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by cliftondavies** [comment]
Thanks @trekab. Both required changes have been applied.

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi @cliftondavies :hand: 
Awesome job on this milestone and implementing the requested changes.
However, it seems that on the last changes, you have modified the .eslintrc file. We should not change this file.

- [ ] We need to use [this version](https://github.com/microverseinc/linters-config/blob/master/react-redux/.eslintrc.json) instead for the .eslintrc file.

Happy coding :computer: 
**Sergio Torres**

**Comment by cliftondavies** [comment]
:wave: @Torres-ssf,

This project milestone requires import of the calculate.js module into the App component, for use in the next milestone. It does seem like like a weird requirement given ESLint will complain about **unused variables**.

I added `"no-unused-vars": "off",` to the .eslintrc file as a temporary solution to the above mentioned issue. It will be removed in the next milestone.

Happy coding!

**Review by bellom — APPROVED** [review]
## Hi @cliftondavies  :clap: 

**Great work making all the necessary corrections from the previous review.**

**Quick one: Don't forget to correct the  ` .eslintrc.json ` in the next milestone.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by cliftondavies** [comment]
Thanks, @bellom! :+1: :memo:

**Pull request merged**
